# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=60)),
                ('given_name', models.CharField(max_length=60)),
                ('nationality', models.CharField(max_length=2)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address_in_china', models.CharField(max_length=250)),
                ('tel', models.CharField(default='86403742', max_length=8)),
                ('school_in_china', models.CharField(default='\u54c8\u5c14\u6ee8\u5de5\u4e1a\u5927\u5b66', max_length=32)),
                ('passport_type', models.CharField(default='\u666e\u901a', max_length=8)),
                ('passport_number', models.CharField(max_length=32)),
                ('passport_expire_date', models.DateField()),
                ('current_visa_category', models.CharField(choices=[('JL', '\u5c45\u7559\u8bc1\u4ef6'), ('MQ', '\u514d\u7b7e'), ('F', ''), ('L', ''), ('M', ''), ('Q2', ''), ('S2', ''), ('X2', ''), ('X1', '')], max_length=2)),
                ('date_of_entry', models.DateField()),
                ('visa_number', models.CharField(max_length=32)),
                ('visa_expire_date', models.DateField()),
                ('student_category', models.CharField(max_length=8)),
                ('is_JW202', models.NullBooleanField()),
                ('graduate_year', models.CharField(max_length=4, null=True)),
                ('graduate_month', models.CharField(max_length=2, null=True)),
                ('tuition_fee_type', models.CharField(choices=[('H', 'Half Year'), ('F', 'Full Year')], max_length=1, null=True)),
            ],
        ),
    ]
